# Generated by Django 5.2 on 2025-11-11 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('participants', models.IntegerField(default=0, verbose_name='参加人数')),
                ('tech', models.TextField(verbose_name='使用技術')),
                ('team', models.CharField(max_length=255, verbose_name='チーム名')),
                ('is_public', models.BooleanField(default=False, verbose_name='公表、非公表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.users', verbose_name='ユーザーID')),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(choices=[('frontend', 'フロントエンド'), ('backend', 'バックエンド'), ('infra', 'インフラ')], max_length=20, verbose_name='カテゴリー')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('url', models.TextField(verbose_name='url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('requirement_id', models.ForeignKey(db_column='requirements_id', on_delete=django.db.models.deletion.CASCADE, to='requirements.requirements')),
            ],
        ),
    ]
