# Generated by Django 5.2 on 2025-11-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='difficulty',
            field=models.CharField(choices=[('low', '初級'), ('mid', '中級'), ('high', '上級')], default='mid', max_length=10, verbose_name='難易度'),
        ),
    ]
