# Generated by Django 5.2 on 2025-11-22 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0002_requirements_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='tech_stacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63, verbose_name='技術名')),
                ('img_url', models.URLField(verbose_name='画像のurl')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='tech',
        ),
        migrations.CreateModel(
            name='requirements_tech_stacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('requirement_id', models.ForeignKey(db_column='requirements_id', on_delete=django.db.models.deletion.CASCADE, to='requirements.requirements')),
                ('tech_stack_id', models.ForeignKey(db_column='tech_stack_id', on_delete=django.db.models.deletion.CASCADE, to='requirements.tech_stacks')),
            ],
        ),
    ]
