# Generated by Django 5.2 on 2025-11-18 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('team_name', models.CharField(max_length=32, verbose_name='チーム名')),
                ('category', models.CharField(choices=[('frontend', 'フロント'), ('backend', 'バックエンド'), ('infra', 'インフラ')], max_length=20)),
                ('content', models.TextField()),
                ('is_answer', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='accounts.users')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
    ]
