# Generated by Django 5.2 on 2025-11-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('フロントエンド', 'frontend'), ('バックエンド', 'backend'), ('インフラ', 'infra')], max_length=20),
        ),
    ]
