# Generated by Django 5.2 on 2025-11-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0003_alter_question_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_answer',
            field=models.BooleanField(default=False),
        ),
    ]
