# Generated by Django 5.2 on 2025-11-20 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=10, verbose_name='ステップ数')),
                ('work_time', models.TextField(verbose_name='稼働想定日数')),
                ('commit_time', models.CharField(choices=[('10h', '10h'), ('15h', '15h'), ('20h', '20h'), ('20h~', '20h~')], max_length=10, verbose_name='週のコミット時間')),
                ('git_skill', models.IntegerField(choices=[(1, 'Git及びGitHubがわからない'), (2, 'Git及びGitHubは使ったことはあるが、言語化は厳しい'), (3, 'Git及びGitHubはだいたいわかっていて、人にも説明できる。')], verbose_name='Git、GitHubについて')),
                ('position', models.CharField(choices=[('frontend', 'フロント'), ('backend', 'バック'), ('infra', 'インフラ')], max_length=255, verbose_name='希望ポジション')),
                ('development_experimence', models.IntegerField(choices=[(1, '開発経験なし'), (2, '開発経験あり（ハッカソン入門コースのみ・実務未経験）'), (3, '実務経験1年未満'), (4, '実務経験1年以上')], verbose_name='開発経験について')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.users', verbose_name='ユーザーID')),
            ],
        ),
        migrations.CreateModel(
            name='Base_skills_Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('base_skill_id', models.ForeignKey(db_column='base_skill_id', on_delete=django.db.models.deletion.CASCADE, to='portral.base_skills', verbose_name='応募フォームID')),
                ('requirement_id', models.ForeignKey(db_column='requirement_id', on_delete=django.db.models.deletion.CASCADE, to='requirements.requirements', verbose_name='要件定義ID')),
            ],
        ),
    ]
